### ISSUE TITLE
Commsec needed to avoid malicious control of the pinball

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/self-aware-pinball#1]
I think we could implement a reduced round Simon + CBC-MAC scheme with sufficient performance for the arduino plus some sort of PAKE key agreement (or just server authenticated?).  Naturally we might face serious consequences if someone like Hendrix or Isaac takes a few months to thwart our pinball games, but that's a risk we'll have to take.

**Comment by kiniry** [comment]
:)

Sounds like a plan...
